# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions/setup-node@v3
        with:
          node-version: 16
          java-version: 11
      - name: Debug
        run: |
          echo "Base branch: ${{ github.base_ref }}"
          echo "Head branch: ${{ github.head_ref }}"
          
      - name: Scanning Head branch
        env: # Setting the Token
          SCANTISTTOKEN: ${{secrets.SCANTISTTOKEN}}
          SCANTIST_IMPORT_URL : "https://api-v4staging.scantist.io/v2/scans/ci-scan/" # add this line if you are setting up on a dedicated scantist server
        run: |
          curl -s https://s3.ap-southeast-1.amazonaws.com/scripts.scantist.com/scripts/test/sca-bom-detect-v4.jar --output sca-bom-detect-v4.jar
          java -jar sca-bom-detect-v4.jar -from Careem

      - name: Checkout Base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
      
      - name: Scanning Base branch
        env: # Setting the Token
          SCANTISTTOKEN: ${{secrets.SCANTISTTOKEN}}
          SCANTIST_IMPORT_URL : "https://api-v4staging.scantist.io/v2/scans/ci-scan/" # add this line if you are setting up on a dedicated scantist server
        run: |
          curl -s https://s3.ap-southeast-1.amazonaws.com/scripts.scantist.com/scripts/test/sca-bom-detect-v4.jar --output sca-bom-detect-v4.jar
          java -jar sca-bom-detect-v4.jar -from Careem -head_ref ${{ github.head_ref }} -base_ref ${{ github.base_ref }}
      
      
